### ISSUE TITLE
Fail running `make` on AdditiveGroves

### ISSUE THREAD

**Issue by willettk** [dariasor/TreeExtra#1]
I'm trying to get started with TreeExtra for the first time. I cloned version 2.5 from the repo and tried to compile both AdditiveGroves and BaggedTrees, getting errors in both. Here's my stack trace for AdditiveTrees:

```
macazon:~/TreeExtra/AdditiveGroves$ make
mkdir -p ../Bin
g++ -O3 -I../shared -I../ThreadPool -c ag_predict.cpp -o ag_predict.o
In file included from ag_predict.cpp:5:
In file included from ./Grove.h:6:
In file included from ../shared/TreeNode.h:10:
../shared/INDdata.h:94:27: error: unknown type name 'streamsize'
        void readData(char* buf, streamsize buflen, floatv& retv, int retvlen);
                                 ^
1 error generated.
make: *** [ag_predict.o] Error 1
```

Are there any requirements which I'm not meeting? I'm working on OSX 10.11.6 with g++ LLVM version 8.0.0 (clang-800.0.42.1).

**Comment by dariasor** [comment]
Hello Kyle,

TreeExtra package works on Windows and Linux, I haven't been supporting it for OSX so far. I'll make it clear in the package description. If you are just starting with the package and want to test how it works with your data, it would be the best to try it on Linux or Windows. If after the tests you decide you really want to use it, but it has to work on OSX, ping me, and we'll figure out what needs to be done to make it work on OSX.

Daria

**Comment by willettk** [comment]
Thanks, Daria. It does compile without errors on Linux for me, which should be fine. I do think it would be very useful to note what platforms in runs on in both the README (#2) and the manuals at [additivegroves.net](additivegroves.net). 

Looking forward to trying it out.

**Comment by dariasor** [comment]
Thanks! Accepted your change to README, updated the general info on additivegroves.net as well.
